### PR TITLE
Change deprecated success() to result->is_success()

### PR DESCRIPTION
**Pull request by oalders**
See https://github.com/mojolicious/mojo/commit/a443003fad

### CODE REVIEW

**Comment by hayajo** [comment]
LGTM! Thank you!!
I will moodify the required version to Mojolicious >= 7.13.

**Comment by oalders** [comment]
Thanks @hayajo!

**Comment by Grinnz** [comment]
This isn't right - ->result->is_success is very different from ->success.

**Comment by oalders** [comment]
@Grinnz what would have been the correct way to do this?

**Comment by Grinnz** [comment]
In #35 I changed it to use the `res` and `error` methods to check equivalent logic - `$tx->success` is mostly equivalent to `$tx->error ? undef : $tx->res`

**Pull request merged**
